const { validate } = require("./validator");

async function run() {
  let exploit = {
    uuid: "12345",
    url: "http://domgo.at/cxss/example/1?payload=abcd&sp=x#<img src=x onerror=taintfoxLog(12345)>",
    settings: { },
    methid: "C"
  };
  var result = {
    "url" : exploit.url,
    "success": false,
    "settings": exploit.settings,
    "method": exploit.method,
    "status": "validated"
  };
  try {
    result = await validate(exploit, []);
  } catch(err) {
    // Catching anything we might have missed
    console.log("Uncaught error: ", err);
    result.success = false;
    result.status = "error";
  }
  console.log(JSON.stringify(result, null, 2));
}

run().catch(console.dir);
